# 1. Tensor

pytorch의 자료형으로 다차원 행렬 (GPU 연산 가능)

### 종류
- Torch.FloatTensor(CPU) torch.cuda.FloatTensor(GPU)

### 선언
- torch.Tensor(size) # default : float
- torch.rand() 0~1 uniform
- torch.randn() 0~1 norm

### 형변환
- torch.Tensor(a) : numpy -> tensor
- a.numpy() : tensor -> numpy

### resize
- a.view(1, 1, 3, 3)

### Merge
- torch.cat((torchA, torchB), dim) dim에 맞추어서 실행

### GPU
```
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
```

In [3]:
import torch

## 1-1. Matrix 선언

In [6]:
# uninstall : empty
x = torch.empty(5, 3)
print(x)

tensor(1.00000e-42 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  3.3967,  0.0000],
        [ 0.0000,  0.5269,  0.0000]])


In [7]:
# install random : rand
x = torch.rand(5, 3)
print(x)

tensor([[ 0.1554,  0.8928,  0.0358],
        [ 0.4852,  0.3175,  0.7861],
        [ 0.1470,  0.7766,  0.8201],
        [ 0.1965,  0.1637,  0.3949],
        [ 0.7513,  0.3184,  0.9416]])


In [8]:
# zeros
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [10]:
# ones
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]])


In [9]:
# install directly 
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [13]:
# reuse method (new_)
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [15]:
# same size로 다시 이용
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.8812, -0.0833,  0.8284],
        [-0.6437,  0.5141,  0.1397],
        [ 0.6424,  0.5085,  1.2271],
        [ 1.1501,  0.8023, -1.8138],
        [-0.2941, -1.1919,  1.5614]])


In [16]:
# size 확인
x.size()

torch.Size([5, 3])

## 1-2. Operation

In [18]:
# add 1
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x+y)

tensor([[ 0.9640,  1.5062,  1.0914],
        [ 0.9771,  1.5082,  0.9750],
        [ 0.8154,  1.1748,  1.1319],
        [ 0.9951,  1.0109,  0.2333],
        [ 1.2511,  0.5551,  0.7894]])


In [19]:
# add 2
torch.add(x, y)

tensor([[ 0.9640,  1.5062,  1.0914],
        [ 0.9771,  1.5082,  0.9750],
        [ 0.8154,  1.1748,  1.1319],
        [ 0.9951,  1.0109,  0.2333],
        [ 1.2511,  0.5551,  0.7894]])

In [20]:
# get result in parameter
result = torch.empty(5, 3)
torch.add(x, y, out = result)

tensor([[ 0.9640,  1.5062,  1.0914],
        [ 0.9771,  1.5082,  0.9750],
        [ 0.8154,  1.1748,  1.1319],
        [ 0.9951,  1.0109,  0.2333],
        [ 1.2511,  0.5551,  0.7894]])

In [21]:
# add inplace 
x.add_(y)

tensor([[ 0.9640,  1.5062,  1.0914],
        [ 0.9771,  1.5082,  0.9750],
        [ 0.8154,  1.1748,  1.1319],
        [ 0.9951,  1.0109,  0.2333],
        [ 1.2511,  0.5551,  0.7894]])

- '_'이 붙으면 inplace를 뜻한다,

## 1-3. indexing and resize

In [23]:
# index like numpy
x[:, 0]

tensor([ 0.9640,  0.9771,  0.8154,  0.9951,  1.2511])

In [27]:
x = torch.randn(4, 4)
x

tensor([[-0.7659,  0.8034,  0.5460, -0.7672],
        [ 1.9126,  0.6220, -0.0210,  0.5657],
        [-0.9713,  0.6203,  1.0684, -0.8132],
        [ 0.0643,  0.9415, -0.2030,  0.7732]])

In [29]:
# reshape
y = x.view(16)
y

tensor([-0.7659,  0.8034,  0.5460, -0.7672,  1.9126,  0.6220, -0.0210,
         0.5657, -0.9713,  0.6203,  1.0684, -0.8132,  0.0643,  0.9415,
        -0.2030,  0.7732])

In [30]:
# -1은 나머지 차원을 뜻한다.
z = x.view(-1, 8)
z

tensor([[-0.7659,  0.8034,  0.5460, -0.7672,  1.9126,  0.6220, -0.0210,
          0.5657],
        [-0.9713,  0.6203,  1.0684, -0.8132,  0.0643,  0.9415, -0.2030,
          0.7732]])

In [31]:
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [32]:
# get item
x = torch.randn(1)
x.item()

-2.09753155708313

## 1-4. Numpy Bridge

In [35]:
# Torch Tensor -> Numpy
a = torch.ones(5)
b = a.numpy()
print(a, b)

tensor([ 1.,  1.,  1.,  1.,  1.]) [ 1.  1.  1.  1.  1.]


In [36]:
a.add_(1)
print(a, b)

tensor([ 2.,  2.,  2.,  2.,  2.]) [ 2.  2.  2.  2.  2.]


In [37]:
import numpy as np

In [38]:
# Numpy -> Tensor
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

[ 1.  1.  1.  1.  1.] tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)


In [39]:
np.add(a, 1, out = a)

array([ 2.,  2.,  2.,  2.,  2.])

In [40]:
print(a, b)

[ 2.  2.  2.  2.  2.] tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


- 동시에 값이 변한다.

## 1-5. CUDA Tensors

- .to method : 

In [41]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device = device)
    x = x.to(device)
    z = x + y
    
    print(z)
    print(z.to("cpu", torch.double))

C:\Users\magenta_jy\Anaconda3\lib\site-packages\torch\cuda\__init__.py:116: UserWarning: 
    Found GPU0 GeForce 710M which is of cuda capability 2.1.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))


RuntimeError: cuda runtime error (8) : invalid device function at c:\programdata\miniconda3\conda-bld\pytorch_1524543037166\work\aten\src\thc\generic/THCTensorMath.cu:15