### Quiz

In [2]:
import numpy as np

##### 1. 5개의 1로 이루어진 정수데이터 타입의 벡터를 만드세요

In [4]:
ar1 = np.ones(5, dtype = 'i')
ar1

array([1, 1, 1, 1, 1], dtype=int32)

##### 2. 10개의 1로 이루어진 정수 데이터 타입의 벡터에서 마지막 3개의 데이터는 5가 들어있는 벡터를 만드세요

In [5]:
ar2 = np.ones(10, dtype='i')
ar2[7:] = 5
ar2

array([1, 1, 1, 1, 1, 1, 1, 5, 5, 5], dtype=int32)

##### 3. 10에서 20까지의 데이터를 가지는 벡터를 만드세요

In [6]:
ar3 = np.arange(10, 21, dtype = 'i')
ar3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], dtype=int32)

##### 4. 위 벡터의 순서를 바꾸세요

In [8]:
ar4 = ar3[::-1]
ar4

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10], dtype=int32)

##### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요

In [13]:
ar5 = np.arange(0, 9).reshape(3, 3)
ar5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 6. 위의 벡터에서  `[[4,5],[7,8]]`  행렬을 만드세요

In [18]:
ar6 = ar5[1:, 1:]
ar6

array([[4, 5],
       [7, 8]])

##### 7. 1에서 10까지의 데이터를 랜덤하게 가지는 3*4 행렬을 만드세요

In [19]:
ar7 = np.random.randint(1, 11, (3, 4))
ar7

array([[ 2, 10,  5,  7],
       [ 4,  1, 10,  7],
       [ 3,  6,  5, 10]])

##### 8. 위에서 만든 행렬의 unique 한 숫자들 리스트와 각숫자의 갯수를 리스트로 나타내세요

In [20]:
ar8, ar9 = np.unique(ar7, return_counts = True)
ar8, ar9

(array([ 1,  2,  3,  4,  5,  6,  7, 10]),
 array([1, 1, 1, 1, 2, 1, 2, 3], dtype=int64))

##### 9. 1에서 12까지에 숫자가 들어간 3*4 행렬을 만드시고 행과 열에 관계없이 데이터를 섞으세요

In [22]:
ar10 = np.random.randint(1, 13, (3, 4))
ar10

array([[ 3,  2,  2,  7],
       [ 8,  4,  8,  4],
       [ 2, 10,  4,  1]])

In [35]:
ar11 = ar10.flatten()
np.random.shuffle(ar11)
ar11.reshape(3, 4)

array([[ 2,  2,  1, 10],
       [ 8,  8,  4,  4],
       [ 4,  3,  2,  7]])

##### 10. 1부터 10까지의 랜덤한 데이터가 들어가는 `3*3`행렬을 만드시고 가장 아래에 위의 데이터를 모두 합한 `1*3`행렬을 추가해서 `4*3`행렬을 만드세요

In [37]:
ar12 = np.random.randint(1, 11, (3, 3))
ar12

array([[6, 5, 3],
       [9, 3, 1],
       [3, 6, 5]])

In [50]:
ar13 = np.sum(ar12, axis = 0)
ar13 = np.vstack([ar12, ar13])
ar13

array([[ 6,  5,  3],
       [ 9,  3,  1],
       [ 3,  6,  5],
       [18, 14,  9]])

##### 11. 10번문제의 결과로 나온 행렬데이터에서 평균값을 출력하고 평균값보다 큰 숫자들만 유니크한 리스트로 나열하세요 (평균값은 소수 둘째 자리까지만 나타내세요)

In [56]:
aver = ar13.mean()
round(aver, 2)

6.8300000000000001

In [61]:
ar14 = ar13[[ar13 > aver]]
ar14 = np.unique(ar14)
ar14

array([ 9, 14, 18])

##### 12. 1부터 20까지의 랜덤숫자를 가지는 5*5 행렬을 만드시고 최대값에는 숫자(MAX), 최소값에는 숫자(MIN)으로 행렬을 바꾸세요

In [63]:
ar15 = np.random.randint(1, 21, (5, 5))
ar15

array([[18,  2,  6, 13, 19],
       [ 6,  3,  5, 18, 13],
       [ 7, 11, 16,  5,  3],
       [ 1,  4, 18, 17, 18],
       [ 8,  6,  2,  2, 19]])

In [66]:
n_max = ar15.max()
n_min = ar15.min()

n_max, n_min

(19, 1)

In [68]:
ar15 = ar15.astype('U21')

for i in np.arange(5):
    for j in np.arange(5):
        if ar15[i, j] == str(n_max):
            ar15[i, j] += "(MAX)"
        if ar15[i, j] == str(n_min):
            ar15[i, j] += "(MIN)"

ar15

array([['18', '2', '6', '13', '19(MAX)'],
       ['6', '3', '5', '18', '13'],
       ['7', '11', '16', '5', '3'],
       ['1(MIN)', '4', '18', '17', '18'],
       ['8', '6', '2', '2', '19(MAX)']],
      dtype='<U21')

##### 13. 100에서 130까지의 랜덤 숫자를 가지는 8*8행렬을 만드시고 3의 배수에는 fiz, 5의 배수에는 buz, 3과 5의 배수는 fbz 문자를 출력하세요

In [75]:
ar16 = np.random.randint(100, 131, (8, 8))
ar16

array([[101, 127, 107, 104, 129, 126, 106, 130],
       [114, 107, 114, 108, 118, 123, 114, 121],
       [111, 117, 129, 102, 124, 117, 119, 122],
       [127, 116, 121, 126, 100, 116, 123, 118],
       [102, 123, 129, 111, 121, 119, 103, 108],
       [112, 101, 111, 130, 103, 129, 126, 117],
       [100, 110, 106, 112, 120, 123, 112, 123],
       [100, 120, 110, 113, 104, 112, 128, 130]])

In [71]:
def changeStr(num):
    if ((num % 3 == 0) and (num % 5 == 0)):
        return "fbz"
    elif (num % 3 == 0):
        return "fiz"
    elif (num % 5 == 0):
        return "buz"
    else:
        return str(num)    

In [80]:
ar17 = [[changeStr(ar16[i, j]) for j in np.arange(8)] for i in np.arange(8)]
np.array(ar17)

array([['101', '127', '107', '104', 'fiz', 'fiz', '106', 'buz'],
       ['fiz', '107', 'fiz', 'fiz', '118', 'fiz', 'fiz', '121'],
       ['fiz', 'fiz', 'fiz', 'fiz', '124', 'fiz', '119', '122'],
       ['127', '116', '121', 'fiz', 'buz', '116', 'fiz', '118'],
       ['fiz', 'fiz', 'fiz', 'fiz', '121', '119', '103', 'fiz'],
       ['112', '101', 'fiz', 'buz', '103', 'fiz', 'fiz', 'fiz'],
       ['buz', 'buz', '106', '112', 'fbz', 'fiz', '112', 'fiz'],
       ['buz', 'fbz', 'buz', '113', '104', '112', '128', 'buz']],
      dtype='<U3')

##### 14. 리스트 컴프리헨션을 이용하여 아래와 같은 규칙은 갖는 행렬을 만드세요

In [78]:
user_input = int(input("number : "))

ar18 = np.array([[(i+1)*(j+1) for j in np.arange(user_input)] for i in np.arange(user_input)])
ar18

number : 5


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [79]:
user_input = int(input("number : "))

ar19 = np.array([[(i+1)*(j+1) for j in np.arange(user_input)] for i in np.arange(user_input)])
ar19

number : 7


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  4,  6,  8, 10, 12, 14],
       [ 3,  6,  9, 12, 15, 18, 21],
       [ 4,  8, 12, 16, 20, 24, 28],
       [ 5, 10, 15, 20, 25, 30, 35],
       [ 6, 12, 18, 24, 30, 36, 42],
       [ 7, 14, 21, 28, 35, 42, 49]])