In [1]:
import torch

# Autograd : automatic differentiation

autograd package 은 텐서의 모든 연산에 대한 미분 값을 가진다.

## Tensor

- `.requires_grad = True` : 연산의 추적이 가능
  - `requires_grad_()` : require_grad 값 변경
- `.backward()` : 사용시 미분, `.grad`로 값을 얻을 수 있다.

- `.detach()` : 미분 추적을 멈추기 위해 
- 'with torch.no_grad()' ??

## Function
- graph
- `.grad_fn` : 연산이 되어 있는 것에 존재
 - requires_grad가 False인 경우, grad_fn = None
- `.backward()` : 미분

In [2]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [3]:
y = x + 2
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [4]:
y.grad_fn

In [5]:
#3(x+2)**2
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


In [14]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [18]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [19]:
b = (a*a).sum()
print(b.grad_fn)


## Gradients

- **grad를 할 x 지정**
  - `x = torch.randn(3, requires_grad=True)`
  
- **x를 이용해 연산 작성**
  - `y = x * x`
  
- **backword(x)로 gradient 입력**
  - `y.backword(gradient)`
  
- **x.grad로 미분값 얻기**
  - x.grad

In [21]:
out.backward()

In [24]:
# d(out)/d(x) - x = 1이 들어감
print(x.grad)

tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


In [26]:
x = torch.randn(3, requires_grad = True)

y = x*2

while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([ 960.6468, -392.5809,  551.8154])


In [27]:
gradient = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(gradient)

print(x.grad)

tensor([  102.4000,  1024.0000,     0.1024])


In [28]:
# requires_grad 취소
with torch.no_grad():
    print((x**2).requires_grad)

False


### summary

#### .grad_fn
gradient function

#### .requires_grad
gradient 사용 여부

#### .backward() 
gradient 값 계산

#### .grad
해당 gradient 값 출력